### ISSUE TITLE
Use sassdoc-extras

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/generator-sassdoc-theme#18]
Keep track of SassDoc `2.0.0` progress and use `sassdoc-extras` instead of `sassdoc-filter` and `sassdoc-indexer`.

**Comment by valeriangalliat** [comment]
This diff can help: 4a4948e7af3c71595c08e361c30a3c61c8ca18d3

**Comment by pascalduez** [comment]
I could use a hand here :-)

**Comment by valeriangalliat** [comment]
I ported the `index.js` and `package.json` changes in #19, feel free to push new options/prompt on top of this PR.
